# model:
#   category: ChatGPT # model category, chosen from ChatGPT, DeepSeek, LLaMA, Qwen, ChatGLM, MiniCPM, OneKE.
#   model_name_or_path: gpt-4o-mini # model name, chosen from the model list of the selected category.
#   api_key: your_api_key # your API key for the model with API service. No need for open-source models.
#   base_url: https://api.openai.com/v1 # base URL for the API service. No need for open-source models.

# extraction:
#   task: RE  # task type, chosen from Base, NER, RE, EE.
#   text: The aid group Doctors Without Borders said that since Saturday , more than 275 wounded people had been admitted and treated at Donka Hospital in the capital of Guinea , Conakry .  # input text for the extraction task. No need if use_file is set to true.
#   constraint: ["nationality", "country capital", "place of death", "children", "location contains", "place of birth", "place lived", "administrative division of country", "country of administrative divisions", "company", "neighborhood of", "company founders"] # Specified entity types for the named entity recognition task. Default set to empty.
#   truth: {"relation_list": [{"head": "Guinea", "tail": "Conakry", "relation": "country capital"}]} # Truth data for the relation extraction task. Structured as a dictionary with the list of relation tuples as the value. Required if set update_case to true.
#   use_file: false # whether to use a file for the input text.
#   mode: quick # extraction mode, chosen from quick, detailed, customized. Default set to quick. See src/config.yaml for more details.
#   update_case: true # whether to update the case repository. Default set to false.
#   show_trajectory: false # whether to display the extracted intermediate steps

model:
  category: DeepSeek 
  model_name_or_path: deepseek-chat 
  api_key: sk-xxxxx
  base_url: https://api.deepseek.com 


extraction:
  task: RE
  text: The aid group Doctors Without Borders said that since Saturday , more than 275 wounded people had been admitted and treated at Donka Hospital in the capital of Guinea , Conakry .
  constraint: ["nationality", "country capital", "place of death", "children", "location contains", "place of birth", "place lived", "administrative division of country", "country of administrative divisions", "company", "neighborhood of", "company founders"]
  truth: {"relation_list": [{"head": "Guinea", "tail": "Conakry", "relation": "country capital"}]} 
  use_file: false 
  mode: quick
  update_case: true 
  show_trajectory: false 